# These substitutions allow the end user to override certain values
substitutions:
  devicename: "shelly-1"
  devicename_h: "Shelly 1"
  is_button: "false"

esphome:
  name: ${devicename}
  friendly_name: ${devicename_h}
  name_add_mac_suffix: true
  project:
    name: Arvernus.Shelly-1
    version: "1.1.0"


esp8266:
  board: esp01_1m
# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://Arvernus/Shelly-for-ESPHome/devices/Shelly1.yaml

wifi:
  # Set up a wifi access point
  ap:
    password: "12345678"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:

time:
  - platform: sntp
    id: sntp_time

switch:
  - platform: gpio
    pin: GPIO4
    id: shelly_relay

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO5
    # small delay to prevent debouncing
    filters:
      - delayed_on_off: 50ms
    # config for state change of input button
    on_state:
      if:
        condition:
          lambda: |-
            return !${is_button};
        then:
          switch.toggle: shelly_relay
    on_click:
      if:
        condition:
          lambda: |-
            return ${is_button};
        then:
          switch.toggle: shelly_relay
    id: button
