name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      devices: ${{ steps.files-array.devices.list }}
    steps:
      - name: Define List of devices
        id: devices
        run: |
          echo ::set-output name=list::$(ls -m *-for-ESPHome.yaml)

  build_esphome_firmware:
    name: Build ESPHome binary for ${{ matrix.file }}
    needs: [prepare]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: ${{ fromJson(needs.prepare.outputs.devices) }}
    outputs:
      esphome-version: ${{ steps.esphome-build.outputs.esphome-version }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: esphome/build-action@v1.1.0
        id: esphome-build
        with:
          yaml_file: ${{ matrix.device }}-for-ESPHome.yaml
      - uses: actions/upload-artifact@v2.3.0
        with:
          name: esphome_firmware/${{ steps.esphome-build.outputs.name }}
          path: ${{ steps.esphome-build.outputs.name }}

  build_mirgration_firmware:
    name: Build Migration Firmware for ${{ matrix.file }}
    needs: [prepare, build_esphome]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: ${{ fromJson(needs.prepare.outputs.devices) }}
      steps: 
        - uses: actions/checkout@v2.4.0
        - uses: actions/download-artifact@v2.1.0
          with:
            name: esphome_firmware*
            path: esphome_firmware
        - name: Build firmware
          uses: yaourdt/mongoose-os-action@v1.0.2
          with:
            mos-yml-path: mirgration_firmware
            build-var: MODEL=${{ matrix.device }}
          id: mos_build
        
  publish:
    name: Publish new firmware and website to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/download-artifact@v2.1.0
        with:
          path: output

      - name: Create single manifest.json
        run: |
          jq -s '{"name": "Shelly for ESPHome", "version": "${{ needs.build.outputs.esphome-version }}", "home_assistant_domain": "esphome", "new_install_skip_erase": false, "builds":.}' output/*/manifest.json > output/manifest.json

      - run: cp -R static/* output

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: output
