name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: Shelly-1-for-ESPHome.yaml
      # CHANGEME: Set the name of your project here:
      name: Shelly for ESPHome
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
